#!/usr/bin/env python3
"""Defines a simple chatting application server."""
import re
import socket

CLIENT_CLOSED_CONNECTION = ''
CLIENT_SENT_NICK = '\A/nick ([a-zA-Z0-9]+)'


class User:
    """
    Defines a user on the scope of the server.

    A User can have its status as UNNAMED or NAMED
    """

    def __init__(self):
        """Define the User object constructor."""
        self.nickname = ""
        self.named = False


def recvln(conn):
    """Return a full line from the connection."""
    print("Recebendo linha...\n")
    char = conn.recv(1)
    buffr = b''
    while True:
        buffr += char
        char = conn.recv(1)
        if char == b'\n' or char == b'':
            print("Linha recebida!\n")
            return buffr


if __name__ == "__main__":
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    s.bind(('', 7000))
    s.listen(5)

    print("Aguardando conexão...\n")
    conexao, endereco = s.accept()
    while True:
        user = User()
        print("Conectado! Recebendo dados...\n")
        message = recvln(conexao)
        message = message.decode()
        if message == CLIENT_CLOSED_CONNECTION:
            print("Usuário encerrou a conexão em seu cliente...\n")
            if user.named:
                ret_message = "/quit %s\n".format(user.nickname)
                print("Enviando %s\n".format(ret_message))
                conexao.send(ret_message.encode())
            conexao.close()
            break
        elif re.match(CLIENT_SENT_NICK, message):
            if not user.named:
                print("Usuário enviou seu nickname/apelido.\n")
                user.nickname = message.split()[1]
                user.status = "NAMED"
                ret_message = "/joined %s\n".format(user.nickname)
                print("Enviando %s\n".format(ret_message))
                conexao.send(ret_message.encode())
            else:
                print("Usuário atualizou seu nickname/apelido.\n")
                old_nick = message.split()[1]
                if old_nick == user.nickname:
                    user.nickname = message.split()[2]
                    ret_message = "/renamed %s\n".format(user.nickname)
                    print("Enviando %s\n".format(ret_message))
                    conexao.send(ret_message.encode())
        else:
            if not user.named:
                print("Error! Enviando resposta padrão /error...\n")
                conexao.send(b"/error\n")
            else:
                ret_message = "%s %s\n".format(user.nickname, message)
                print("Enviando %s\n".format(ret_message))
                conexao.send(ret_message.encode())
        print("Enviado! Repetindo fluxo...\n")
    print("Conexão encerrada.\n")
